app:
  name: lalala_im_receive_dev
  version: 1.0.0
  host: ""
  run_mode: debug
  auth:
    secret: lalala
server:
  http:
    port: 3001
    read_timeout: 10
    write_timeout: 10
data:
  mongo:
    url: mongodb://admin:lalala@192.168.242.128:27017/?authSource=admin
    database: la_DB
  redis:
    addr: 192.168.242.128:6379
    password: ''
log:
  log_path:
  log_level: errors
  log_encode_mod: console
  is_console: true

third_party:
  email:
    sender:
    name:
    pass:
    host: smtp.163.com
    port: 465
  ali_oss:
    access_key_id:
    access_key_secret:
    endpoint: oss-cn-beijing.aliyuncs.com